AllCops:
  Exclude:
    - 'db//*'
    - 'config//*'
    - 'test//*'
    - 'bin//*'
  DisabledByDefault:
    - 'Style/Documentation'
Metrics/MethodLength:
  Max: 45
Metrics/LineLength:
  Max: 500
Metrics/BlockLength:
  Max: 150