AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

Encoding:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Rails/HasAndBelongsToMany:
  Enabled: false